[book]
authors = ["Jonas da Silva"]
language = "en"
multilingual = false
src = "src"
title = "whichlang"

[build]
extra-watch-dirs = ["scripts"]

[output.html]
additional-js = ["scripts/whichlang.js"]
additional-css = ["theme/whichlang.css"]
git-repository-url = "https://github.com/phoenixr-codes/mdbook-whichlang/tree/master/"
edit-url-template = "https://github.com/phoenixr-codes/mdbook-whichlang/edit/master/book/{path}"
